### ISSUE TITLE
Incompatible with Woocommerce 'High-Performance order storage', it shouldn't be activated. 

### ISSUE THREAD

**Issue by EC1618** [fingent-corp/simplify-woocommerce-mastercard-module#15]
I am trying to install this plugin on new website but it comes up with a message like the below.   

"This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated. "

![image](https://github.com/fingent-corp/simplify-woocommerce-mastercard-module/assets/168695022/b80b05a8-3e3d-4996-8205-2f9565c28784)

Can't be ignored as it then causes a crash at checkout.

WooCommerce Version 8.8.3
Wordpress 6.5.2

**Comment by jineshpv** [comment]
We've recently launched version 2.4.2, which includes support for HPOS and the WooCommerce checkout block. We encourage you to give it a try.

**Comment by jineshpv** [comment]
@EC1618 
We believe the issue has been resolved on your end. If you have any further questions, please feel free to raise a new ticket through the Customer Portal at (https://mpgsfgs.atlassian.net/servicedesk/customer/portals)
